name: thztools
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black
  - coverage
  - jupyter
  - matplotlib
  - mypy
  - numdifftools
  - numpydoc
  - pandas
  - pip
  - pydata-sphinx-theme
  - pytest-cov
  - ruff
  - scipy
  - sphinx
  - tomli
  - pip:
    - -e ../
